#include "patternfab/SvgExport.h"

#include <QPainter>
#include <QPainterPath>
#include <QRectF>
#include <QSvgGenerator>

#include <cmath>
#include <stdexcept>

namespace patternfab {

namespace {

// QSvgGenerator computes its declared physical width/height (with an
// explicit "mm" suffix, verified empirically) as size-in-pixels /
// resolution-in-dpi * 25.4. Setting resolution to 25.4 * kMmPrecisionScale
// and size to widthMm/heightMm * kMmPrecisionScale makes that declared size
// equal to widthMm/heightMm mm exactly (up to sub-micron integer rounding
// on QSize, which is integral) -- while the QRectF viewBox keeps the actual
// drawing coordinate mapping at full floating-point precision regardless.
constexpr double kMmPrecisionScale = 1000.0;

} // namespace

void exportPatternToSvg(const Pattern &pattern, const std::string &path) {
    const double widthMm = pattern.params.specimenWidthMm;
    const double heightMm = pattern.params.specimenHeightMm;
    if (widthMm <= 0.0 || heightMm <= 0.0) {
        throw std::runtime_error("exportPatternToSvg: specimen dimensions must be positive");
    }

    QSvgGenerator generator;
    generator.setFileName(QString::fromStdString(path));
    generator.setResolution(static_cast<int>(25.4 * kMmPrecisionScale));
    generator.setSize(QSize(static_cast<int>(std::llround(widthMm * kMmPrecisionScale)),
                            static_cast<int>(std::llround(heightMm * kMmPrecisionScale))));
    generator.setViewBox(QRectF(0.0, 0.0, widthMm, heightMm));
    generator.setTitle("PatternFab pattern");
    generator.setDescription("Generated by PatternFab");

    QPainter painter;
    if (!painter.begin(&generator)) {
        throw std::runtime_error("exportPatternToSvg: failed to begin painting: " + path);
    }
    painter.setPen(Qt::NoPen);
    painter.setBrush(Qt::black);

    for (const auto &primitive : pattern.primitives) {
        if (primitive.shape == PrimitiveShape::Polygon) {
            if (primitive.verticesMm.empty()) {
                continue;
            }
            QPainterPath polygonPath;
            polygonPath.moveTo(primitive.verticesMm[0].first, primitive.verticesMm[0].second);
            for (std::size_t i = 1; i < primitive.verticesMm.size(); ++i) {
                polygonPath.lineTo(primitive.verticesMm[i].first, primitive.verticesMm[i].second);
            }
            polygonPath.closeSubpath();
            painter.drawPath(polygonPath);
        } else {
            painter.drawEllipse(QPointF(primitive.centerXMm, primitive.centerYMm), primitive.radiusXMm,
                                 primitive.radiusYMm);
        }
    }
    painter.end();
}

} // namespace patternfab
